### ISSUE TITLE
Feature Request: Extra Character support

### ISSUE THREAD

**Issue by Lachlan95Thompson** [D0-0K/adwaitapod#1]
Hey,

I really like this theme, however I listen to music that have titles or album names in other languages.  The current font in use only supports English characters. Is it possible to add an option for a font that allows for a wide array of characters?

I would really appreciate it.
Thank you.

**Comment by D0-0K** [comment]
Hi!

 What kind of fonts are you looking for? I have downloads for Simplified Chinese, Japanese and Korean combo fonts (as well as one with all three) in the releases section [here](https://github.com/D0-0K/adwaitapod/releases/tag/v.1).

**Comment by Lachlan95Thompson** [comment]
I'm not sure what font per-se, but would you know of any fonts that have English, Korean, Russian, Japanese and Chinese included? I know GNU Unifont that comes with Rockbox includes these characters, but changing to this font messes with the theme itself as obviously it wasn't designed with this font in mind.
I don't necessarily want to change the language of the theme, but I would like to be able to see these foreign characters.
I hope I am not asking too much.

**Comment by D0-0K** [comment]
Ah! Yeah, the font is tuned in a way to best fit the style, there are also problems with using larger fonts that I'm working on accomodating for right now. The next release mightn't be for another couple of months, but I'll try to get Russian support in! In the meantime, the [English+Korean,Japanese&Chinese](https://github.com/D0-0K/adwaitapod/releases/download/v.1/Cantarell.+.CJK.zip) should cover some of your needs hopefully!

**Comment by Lachlan95Thompson** [comment]
Hi, sorry for the late reply.
This font is great!  It seems the Russian language works too.

Is it possible to include some of these characters too? Other than that, every character on my iPod shows with the current fonts.
ᗡ𝘈▲ᴗ˳⍙❅◑෴⚆「」

I appreciate your hard work.

**Comment by D0-0K** [comment]
Oh! That's a great surprise! Thanks so much for testing it. As for the characters, I can definitely support them, I'll do some research and add other common characters while I'm at it. The next release should be ready by late November or so, will give you a ping when it's ready!

**Comment by Lachlan95Thompson** [comment]
Hey I am just following up to ask if any of the fonts in the recent update include any special characters?
Thanks!

**Comment by D0-0K** [comment]
Not yet! Sadly I haven't had too much time to devote to this, but I'm hoping by the end of january to have another update completed which will add this as well as some more features. I want to make sure I do it right, probably will do an analysis of commonly used special characters in songs etc. I'll let you know how it goes

**Comment by D0-0K** [comment]
Hey there, I've started work on the next release of adwaitapod and will be putting together a new font supporting these characters. If you're interesting in testing it early for me, send me an [email](https://d00k.net/about/#where-to-find-me) and I'll send them on!

**Comment by D0-0K** [comment]
Some support has been added, though without fixes from Rockbox, further unicode support is not possibly. So for now I'm closing this (mostly cause I don't see Rockbox fixing this)
