### ISSUE TITLE
Adwaitapod doesn't work as intended.

### ISSUE THREAD

**Issue by Kale-ish** [D0-0K/adwaitapod#21]
**Device**: iPod 6th gen
**Rockbox Version**: Release 3.15.
**Description**: The theme doesn't load properly and the only part that works as intended is the Now Playing screen.
Description of the issue. The theme doesn't have the custom main and sub menus, the quickscreen, and the lockscreen.
This issue persists even after deleting every file related to adwaitapod and reinstalling it both manually and through the Rockbox Utility.
(Sorry if this is poorly formatted or explained)

**Comment by D0-0K** [comment]
Hi! Thank you for the report, I think I can understand your issue. Would you say the screen looks like the following below?
![image](https://github.com/D0-0K/adwaitapod/assets/66568057/abe3e5ca-db2b-47dc-9f54-e61e7691325f)

What specific adwaitapod theme are you using? (adwaitapod, simplified, dark, light etc)

**Comment by D0-0K** [comment]
Oh also just wondering where you downloaded the theme from? (rockbox themes, the Utility app, or github)

**Comment by Kale-ish** [comment]
The screen does appear similar to the image shown, the theme that I am using is adwaitapod_dark, and I have downloaded the theme from github.

**Comment by D0-0K** [comment]
Lovely, thank you for the report! Downloading a simulator right now to test the file

**Comment by D0-0K** [comment]
Problem identified, a translation string not supported in the last official release (daily builds only) Will be fixed and uploaded within the next 30 minutes!

Thank you very, very much for reaching out about this!

**Comment by D0-0K** [comment]
This is now live in the releases section @Kale-ish!

**Comment by Kale-ish** [comment]
Okay, thank you for fixing the issue!

**Comment by D0-0K** [comment]
Thanks again for reaching out, apologies on my end for the sloppy testing!

I'll leave this open for now, just in case, but will close in a few days if no more reports.

**Comment by neofright** [comment]
Loads correctly on my ipod6g build (nightly equivalent).

**Comment by D0-0K** [comment]
Closing this since it seems to be no longer an issue :)
