### ISSUE TITLE
adwaita dark simplified has artifacting when changing the volume on the wps

### ISSUE THREAD

**Issue by neofright** [D0-0K/adwaitapod#22]
**Device**: ipod6g
**Rockbox Version**: [My own build](https://github.com/neofright/rockbox), in line with e5ecff3 [upstream](https://github.com/Rockbox/rockbox/commits/master)
**Adwaitapod Theme**: adwaitapod dark simplified
**Downloaded From**: Github, the latest release and large source code zip
**Description**:
none of the other themes have the same weird looking volume changing image with bleeding white around the black oval. I suspect this is a bug with adwaitapod dark simplified.
![dump 230713-202433](https://github.com/D0-0K/adwaitapod/assets/68615872/80bdf371-3a52-44b5-bf0e-dca03faac0d8)

**Comment by D0-0K** [comment]
Hi there! Thanks for the report (screenshot is really helpful!). You're right that looks like the volume background that should be used in the Light variants, not the dark. Will take a look and change it out

**Comment by neofright** [comment]
```
neofright:adwaitapod_dark neofright$ md5sum ../../../../adwaitapod_dark_simplified/.rockbox/wps/adwaitapod_dark_simplified/Volume*
e98d3be017c383504773acde863f2e6a  ../../../../adwaitapod_dark_simplified/.rockbox/wps/adwaitapod_dark_simplified/VolumeBackdrop.bmp
f29cf7305c1ea7ed9a8ec207dbc94b8c  ../../../../adwaitapod_dark_simplified/.rockbox/wps/adwaitapod_dark_simplified/VolumeIcons.bmp
b7c97c0c3b0122b075ea1c3d7558f2c4  ../../../../adwaitapod_dark_simplified/.rockbox/wps/adwaitapod_dark_simplified/VolumePromptIcons.bmp
2c6ad2cc1b00e80baa242cb53ff7f534  ../../../../adwaitapod_dark_simplified/.rockbox/wps/adwaitapod_dark_simplified/VolumeSlider.bmp
9bb63877674a60f236b44dc69b46998c  ../../../../adwaitapod_dark_simplified/.rockbox/wps/adwaitapod_dark_simplified/VolumeSliderBackdrop.bmp
795745de738426b522a22124ba3a512e  ../../../../adwaitapod_dark_simplified/.rockbox/wps/adwaitapod_dark_simplified/VolumeSliderEnd.bmp
neofright:adwaitapod_dark neofright$ md5sum Volume*
914cc92a30d302c1b56db9e79a1f7b85  VolumeBackdrop.bmp
f29cf7305c1ea7ed9a8ec207dbc94b8c  VolumeIcons.bmp
b7c97c0c3b0122b075ea1c3d7558f2c4  VolumePromptIcons.bmp
2c6ad2cc1b00e80baa242cb53ff7f534  VolumeSlider.bmp
9bb63877674a60f236b44dc69b46998c  VolumeSliderBackdrop.bmp
795745de738426b522a22124ba3a512e  VolumeSliderEnd.bmp
```

Looks like only `VolumeBackdrop.bmp` needs to be swapped.

**Comment by D0-0K** [comment]
Yeah, must've been one file I missed making that version. Making the change now.

**Comment by neofright** [comment]
Can confirm swapping `VolumeBackdrop.bmp` from `.rockbox/wps/adwaitapod_dark_simplified/` works.

**Comment by D0-0K** [comment]
Just realised the release you used only linked the source code. This is fixed in the new release too, so if you're looking for extras like wallpapers etc they're there :)
