### ISSUE TITLE
Battery image does not reflect actual percentage or state

### ISSUE THREAD

**Issue by Lachlan95Thompson** [D0-0K/adwaitapod#25]
Device: iPod Video 5.5th gen
Rockbox Version: nightly build 'Ver. 100e9ac137-230417'
Adwaitapod Theme: adwaitapod dark simplified (3.2)
Downloaded From: Github

Description:
I have removed the previous versions of adwaitapod and installed dark simplified from this github.
I have noticed however, that the battery in WPS and menu mode is always at 50% and does not change appearence when charging.
However, when I hold down menu to select shuffle/repeat, etc, the battery appears correctly (correct percentage, shows when charging, etc).

It does not appear to be an issue with charging itself. Just the reflection of the actual % and state in WPS and menu mode.

I believe this to be a bug.

**Comment by D0-0K** [comment]
Hi Lachlan! Thanks for bringing this to my attention. I don't even need to find this, I know exactly what I've done lmao. Battery percentages were set for screenshots at 50% and I must've forgotten to change them back!

Will be fixed and released in about 30 mins!

**Comment by D0-0K** [comment]
Version 3.3 is out, fixing this oversight! Thanks again for letting me know! :)
