### ISSUE TITLE
adwaitapod dark simplified's rounded corners on line selectors are offset

### ISSUE THREAD

**Issue by jfurrow** [D0-0K/adwaitapod#28]
**Device**: iPod 5th gen
**Rockbox Version**: Release 3.15
**Adwaitapod Theme**: adwaitapod dark simplified
**Downloaded From**: Rockbox Utility
**Description**: The rounded corners are offset on the line selectors for the simplified variant, but seem fine for the non-simplified variant.

| **adwaitapod dark simplified** | **adwaitapod dark** |
| --- | --- |
| <img width="522" alt="Screenshot 2023-09-21 at 11 58 47 PM" src="https://github.com/D0-0K/adwaitapod/assets/1134755/80dd2598-103c-46c5-97db-ed2ee0e5bf0e"> <img width="520" alt="Screenshot 2023-09-21 at 11 58 02 PM" src="https://github.com/D0-0K/adwaitapod/assets/1134755/73d88ff0-ebc6-4112-b079-a7e2db98727f"> | <img width="516" alt="Screenshot 2023-09-21 at 11 58 35 PM" src="https://github.com/D0-0K/adwaitapod/assets/1134755/71c1cfdd-794d-47c6-93f6-9cf3f1aeb2a0"> <img width="480" alt="Screenshot 2023-09-21 at 11 58 15 PM" src="https://github.com/D0-0K/adwaitapod/assets/1134755/36207517-3fa4-4ecc-aa40-6779841ea0e5"> |

---

This theme is absolutely beautiful, thanks for working so hard on it!

**Comment by D0-0K** [comment]
Can confirm this myself! No clue how I managed to miss that for so long. The simplified theme has it's own font for the main menus with larger padding, which appears to be missing. Will have a fix up ASAP.

**Comment by D0-0K** [comment]
Fix is complete, will be out later today since I've decided I'm going to take this opportunity to create and release a downloadable accent colours pack :)

**Comment by jfurrow** [comment]
Wow! Thanks very much. Looking forward to checking out the accent colors pack!! 😁

**Comment by D0-0K** [comment]
Might be a couple of days since the accent colours is quite an asset-heavy task, however in the meantime the [github releases](https://github.com/D0-0K/adwaitapod/releases/tag/v.3.3) aren't affected if you're comfortable manually downloading!

Did want to say thanks for the really detailed bug report! Makes fixing these things super easy, and thanks of course for the support!

**Comment by D0-0K** [comment]
Fixes done, and uploading to the Rockbox site currently. Thanks again for the great bug report! :)
