### ISSUE TITLE
The selector in difficult to see in direct sunlight

### ISSUE THREAD

**Issue by edhelas** [D0-0K/adwaitapod#3]
Hi, thanks for this awesome theme.

I'm using the dark version and I had some issues to see which album or artist I selected on my iPod when scrolling in direct sunlight. Having more contrast between the dark background and the gray-ish selector might help a bit :)

**Comment by D0-0K** [comment]
Hi, thanks for leaving feedback!
 I actually just started working on this problem yesterday, it's been a common issue in V1. If you don't mind, would you be cool with testing the new colour and seeing how it feels? You can change the colour in Settings>Theme Settings>Colours>Line Selector Colours>Primary Colour. The new value is 525152 (or R10,G20,B10). Thanks!

**Comment by edhelas** [comment]
Yes looks better :) ! Thanks

**Comment by D0-0K** [comment]
Awesome! Thanks for testing. Keep an eye out hopefully next week for the full release of v2!
