### ISSUE TITLE
Cannot change volume in quickscreen

### ISSUE THREAD

**Issue by samuelrhaynes** [D0-0K/adwaitapod#31]
**Device**: iPod 6th gen Classic
**Rockbox Version**: Release 3.15 
**Adwaitapod Theme**: All versions of 3.0 onwards (dark and simplified)
**Downloaded From**: Github, Rockbox Utility, Rockbox Theme site. (tried all versions)
**Description**: Cannot change volume or brightness in the Quickscreen on any of the 4 themes. If unlock the new design of quickscreen, can change brightness but still cannot change volume. I've turned the wheel clicker noise on to confirm it is registering the scrollwheel in the quickscreen, it is registering but volume is not changing.

**Comment by D0-0K** [comment]
The volume adjustment on the quickscreen was only added in 2021 it turns out! (this is [the patch that added it](https://gerrit.rockbox.org/r/c/rockbox/+/3125)) Switching to a daily build should allow you to adjust the volume from the quickscreen with the scroll wheel. :)

**Comment by samuelrhaynes** [comment]
Ah how embarrassing, updating to rockbox daily build instead of release 3.15 fixed this. Thank you
