### ISSUE TITLE
Freeze on USB screen after unplugging

### ISSUE THREAD

**Issue by D0-0K** [D0-0K/adwaitapod#7]
**Model**: Gen 6/7
**Version**: Unknown
**Description**:
After unplugging from a computer, the theme can freeze on the lockscreen. Possibly related the the lockscreen method's code. Needs more testing.

**Comment by D0-0K** [comment]
Possibly fixed with latest change, but keeping open till confirmed.

**Comment by 82MHz** [comment]
Confirmed fixed for me!

**Comment by D0-0K** [comment]
> Confirmed fixed for me!

YES! Thank you for the help testing :) Fantastic it's fixed!
